[theme]
primaryColor = "#00acad"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a2744"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
